import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const toolsDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(toolsDirectory, "..");
const sourcePath = join(toolsDirectory, "data", "bountiful_crops.json");
const cropBlocksRoot = join(projectRoot, "BP", "blocks", "addons", "bc", "crops");
const cropLootRoot = join(projectRoot, "BP", "loot_tables", "bc", "crops");
const seedLootRoot = join(projectRoot, "BP", "loot_tables", "bc", "seeds");
const itemsRoot = join(projectRoot, "BP", "items");
const seedSynthesizerUiPath = join(
  projectRoot,
  "RP",
  "ui",
  "recipes",
  "seed_synthesizer.json"
);
const runtimeOutputPath = join(
  projectRoot,
  "BP",
  "scripts",
  "config",
  "recipes",
  "bountifulCrops.generated.js"
);

const source = JSON.parse(await readFile(sourcePath, "utf8"));
const definitions = normalizeDefinitions(source);
await validateItemDefinitions(definitions);
await generateRuntimeModule(definitions);
await generateLootTables(definitions);
await updateCropBlocks(definitions);
await updateSeedSynthesizerUi(definitions);

console.log(`Generated ${definitions.length} Bountiful Crops definitions.`);

function normalizeDefinitions(rawSource) {
  if (!rawSource || typeof rawSource !== "object") throw new TypeError("Invalid crop source");
  if (!Array.isArray(rawSource.crops)) throw new TypeError("crops must be an array");

  const uniqueKeys = new Set();
  const uniqueCropIds = new Set();
  const uniqueSeedIds = new Set();
  const uniqueLootFiles = new Set();

  return rawSource.crops.map(rawCrop => {
    const tierSettings = rawSource.tiers?.[String(rawCrop.tier)];
    if (!tierSettings) throw new Error(`Missing tier settings for ${rawCrop.key}`);
    validateGrowthInterval(tierSettings.growthInterval, rawCrop.key);
    if (!(tierSettings.seedChance > 0 && tierSettings.seedChance < 1)) {
      throw new Error(`Invalid seed chance for tier ${rawCrop.tier}`);
    }
    if (typeof rawCrop.soil !== "string" || !rawCrop.soil.includes(":")) {
      throw new Error(`Invalid soil in ${rawCrop.key}`);
    }
    if (!Array.isArray(rawCrop.drops) || rawCrop.drops.length === 0) {
      throw new Error(`Crop ${rawCrop.key} must define at least one drop`);
    }

    assertUnique(uniqueKeys, rawCrop.key, "key");
    assertUnique(uniqueCropIds, rawCrop.cropId, "cropId");
    assertUnique(uniqueSeedIds, rawCrop.seedId, "seedId");
    assertUnique(uniqueLootFiles, rawCrop.lootFile, "lootFile");

    const drops = rawCrop.drops.map(drop => {
      if (typeof drop.item !== "string" || !drop.item.includes(":")) {
        throw new Error(`Invalid drop item in ${rawCrop.key}`);
      }
      const chance = Number(drop.chance ?? 1);
      if (!(chance > 0 && chance <= 1)) throw new Error(`Invalid drop chance in ${rawCrop.key}`);
      validateAmount(drop.amount, rawCrop.key);
      return { item: drop.item, amount: drop.amount, chance };
    });

    return {
      ...rawCrop,
      growthInterval: [...tierSettings.growthInterval],
      seedChance: Number(tierSettings.seedChance),
      drops
    };
  });
}

function assertUnique(values, value, label) {
  if (typeof value !== "string" || value.length === 0) throw new Error(`Invalid ${label}`);
  if (values.has(value)) throw new Error(`Duplicate ${label}: ${value}`);
  values.add(value);
}

function validateAmount(amount, key) {
  if (Number.isInteger(amount) && amount > 0) return;
  if (
    Array.isArray(amount) &&
    amount.length === 2 &&
    Number.isInteger(amount[0]) &&
    Number.isInteger(amount[1]) &&
    amount[0] > 0 &&
    amount[1] >= amount[0]
  ) return;
  throw new Error(`Invalid drop amount in ${key}`);
}

function validateGrowthInterval(interval, key) {
  if (
    !Array.isArray(interval) ||
    interval.length !== 2 ||
    !Number.isInteger(interval[0]) ||
    !Number.isInteger(interval[1]) ||
    interval[0] <= 0 ||
    interval[1] < interval[0]
  ) throw new Error(`Invalid growth interval in ${key}`);
}

async function generateRuntimeModule(crops) {
  const serialized = JSON.stringify(crops, null, 2);
  const moduleSource = `// This file is generated by tools/generate_bountiful_crops.mjs.\n` +
`// Edit tools/data/bountiful_crops.json, then run the generator.\n\n` +
`export const BOUNTIFUL_CROP_DEFINITIONS = Object.freeze(${serialized});\n\n` +
`export const BOUNTIFUL_CROPS_BY_BLOCK = Object.freeze(Object.fromEntries(\n` +
`  BOUNTIFUL_CROP_DEFINITIONS.map(definition => [definition.cropId, definition])\n` +
`));\n\n` +
`export const BOUNTIFUL_CROPS_BY_SEED = Object.freeze(Object.fromEntries(\n` +
`  BOUNTIFUL_CROP_DEFINITIONS.map(definition => [definition.seedId, definition])\n` +
`));\n\n` +
`export const cropData = Object.freeze(Object.fromEntries(\n` +
`  BOUNTIFUL_CROP_DEFINITIONS.map(definition => [definition.cropId, {\n` +
`    seed: definition.seedId,\n` +
`    loot: \`bc/crops/\${definition.lootFile}\`,\n` +
`    tier: definition.tier,\n` +
`    drops: definition.drops,\n` +
`    seedChance: definition.seedChance\n` +
`  }])\n` +
`));\n\n` +
`export const bountifulPlantsData = Object.freeze(Object.fromEntries(\n` +
`  BOUNTIFUL_CROP_DEFINITIONS.map(definition => [definition.seedId, {\n` +
`    cost: definition.cost,\n` +
`    drops: [\n` +
`      ...definition.drops.map(drop => ({\n` +
`        item: drop.item,\n` +
`        amount: Array.isArray(drop.amount) ? [...drop.amount] : drop.amount,\n` +
`        chance: drop.chance\n` +
`      })),\n` +
`      { item: definition.seedId, amount: 1, chance: definition.seedChance }\n` +
`    ]\n` +
`  }])\n` +
`));\n`;

  await writeFile(runtimeOutputPath, moduleSource, "utf8");
}

async function generateLootTables(crops) {
  for (const crop of crops) {
    const maturePools = crop.drops.map(drop => createDropPool(drop));
    maturePools.push({
      rolls: 1,
      conditions: [{ condition: "random_chance", chance: crop.seedChance }],
      entries: [{ type: "item", name: crop.seedId }]
    });

    await writeJson(join(cropLootRoot, `${crop.lootFile}.json`), { pools: maturePools });
    await writeJson(join(seedLootRoot, `${crop.lootFile}.json`), {
      pools: [{ rolls: 1, entries: [{ type: "item", name: crop.seedId }] }]
    });
  }

  const expectedFiles = new Set(crops.map(crop => `${crop.lootFile}.json`));
  await validateExactJsonFiles(cropLootRoot, expectedFiles, "mature loot table");
  await validateExactJsonFiles(seedLootRoot, expectedFiles, "seed loot table");
}

function createDropPool(drop) {
  const entry = { type: "item", name: drop.item };
  if (drop.amount !== 1) {
    entry.functions = [{
      function: "set_count",
      count: Array.isArray(drop.amount)
        ? { min: drop.amount[0], max: drop.amount[1] }
        : drop.amount
    }];
  }

  const pool = { rolls: 1, entries: [entry] };
  if (drop.chance < 1) pool.conditions = [{ condition: "random_chance", chance: drop.chance }];
  return pool;
}

async function updateCropBlocks(crops) {
  const definitionsByBlock = new Map(crops.map(crop => [crop.cropId, crop]));
  const files = await collectJsonFiles(cropBlocksRoot);
  const foundBlocks = new Set();

  for (const filePath of files) {
    const document = JSON.parse(await readFile(filePath, "utf8"));
    const block = document["minecraft:block"];
    const identifier = block?.description?.identifier;
    const definition = definitionsByBlock.get(identifier);
    if (!definition) throw new Error(`Unregistered crop block: ${identifier ?? relative(projectRoot, filePath)}`);

    foundBlocks.add(identifier);
    block.components["minecraft:tick"] = {
      interval_range: [...definition.growthInterval],
      looping: true
    };
    block.components["minecraft:loot"] = `loot_tables/bc/seeds/${definition.lootFile}.json`;

    const placementConditions = block.components["minecraft:placement_filter"]?.conditions;
    if (!Array.isArray(placementConditions) || !placementConditions[0]) {
      throw new Error(`Missing placement filter: ${identifier}`);
    }
    placementConditions[0].block_filter = [definition.soil];

    const maturePermutation = block.permutations.find(permutation =>
      typeof permutation.condition === "string" && permutation.condition.includes("age')==5")
    );
    if (!maturePermutation) throw new Error(`Missing mature permutation: ${identifier}`);
    maturePermutation.components["minecraft:loot"] = `loot_tables/bc/crops/${definition.lootFile}.json`;

    await writeJson(filePath, document);
  }

  for (const crop of crops) {
    if (!foundBlocks.has(crop.cropId)) throw new Error(`Missing crop block: ${crop.cropId}`);
  }
}

async function validateItemDefinitions(crops) {
  const itemFiles = await collectJsonFiles(itemsRoot);
  const items = new Map();

  for (const filePath of itemFiles) {
    const document = JSON.parse(await readFile(filePath, "utf8"));
    const item = document["minecraft:item"];
    const identifier = item?.description?.identifier;
    if (identifier) items.set(identifier, item);
  }

  for (const crop of crops) {
    const seedItem = items.get(crop.seedId);
    if (!seedItem) throw new Error(`Missing seed item: ${crop.seedId}`);
    if (seedItem.components?.["minecraft:block_placer"]?.block !== crop.cropId) {
      throw new Error(`Seed does not place canonical crop: ${crop.seedId}`);
    }

    for (const drop of crop.drops) {
      if (drop.item.startsWith("utilitycraft:") && !items.has(drop.item)) {
        throw new Error(`Missing custom drop item: ${drop.item}`);
      }
    }
  }
}

async function updateSeedSynthesizerUi(crops) {
  const document = JSON.parse(await readFile(seedSynthesizerUiPath, "utf8"));

  for (const crop of crops) {
    const seedName = crop.seedId.split(":")[1];
    const panelName = `seed_${seedName}_results`;
    const panel = document[panelName];
    if (!panel || !Array.isArray(panel.controls)) {
      throw new Error(`Missing Seed Synthesizer drop panel: ${panelName}`);
    }

    const strips = panel.controls
      .map(control => Object.entries(control).find(([name]) =>
        name.endsWith("@uc.seed_drop_result_strip")
      ))
      .filter(Boolean);

    if (strips.length !== crop.drops.length + 1) {
      throw new Error(`Unexpected drop row count in ${panelName}`);
    }

    crop.drops.forEach((drop, index) => {
      const [controlName, row] = strips[index];
      validateDropRow(controlName, drop.item, index, panelName);
      row["$result_chance_text"] = formatUiChance(drop.chance);
      row["$result_amount_text"] = formatUiAmount(drop.amount);
    });

    const [seedControlName, seedRow] = strips.at(-1);
    validateDropRow(seedControlName, crop.seedId, crop.drops.length, panelName);
    seedRow["$result_chance_text"] = formatUiChance(crop.seedChance);
    seedRow["$result_amount_text"] = "x1";
  }

  await writeFile(
    seedSynthesizerUiPath,
    `${JSON.stringify(document, null, 2)}\n`,
    "utf8"
  );
}

function validateDropRow(controlName, itemId, index, panelName) {
  const itemName = itemId.split(":")[1];
  const expectedPrefix = `${itemName}_${index}_strip@`;
  if (!controlName.startsWith(expectedPrefix)) {
    throw new Error(
      `Drop row mismatch in ${panelName}: expected ${expectedPrefix}, found ${controlName}`
    );
  }
}

function formatUiChance(chance) {
  return `${Number((chance * 100).toFixed(4))}%%`;
}

function formatUiAmount(amount) {
  return Array.isArray(amount) ? `x${amount[0]}-${amount[1]}` : `x${amount}`;
}

async function validateExactJsonFiles(directory, expectedFiles, label) {
  const actualFiles = new Set(
    (await readdir(directory, { withFileTypes: true }))
      .filter(entry => entry.isFile() && entry.name.endsWith(".json"))
      .map(entry => entry.name)
  );

  for (const fileName of expectedFiles) {
    if (!actualFiles.has(fileName)) throw new Error(`Missing ${label}: ${fileName}`);
  }
  for (const fileName of actualFiles) {
    if (!expectedFiles.has(fileName)) throw new Error(`Unregistered ${label}: ${fileName}`);
  }
}

async function collectJsonFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const entryPath = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collectJsonFiles(entryPath));
    else if (entry.isFile() && entry.name.endsWith(".json")) files.push(entryPath);
  }
  return files;
}

async function writeJson(filePath, value) {
  await writeFile(filePath, `${JSON.stringify(value, null, "\t")}\n`, "utf8");
}
